apiVersion: v1
kind: Pod
metadata:
  name: resourse
  labels: 
    project: roboshop
spec:
  containers:
  -  name: nginx
     image: nginx
     resources:
       requests: # soft limit
         memory: "64Mi"
         cpu: "100m"
       limits: # hard limit
         memmory: "128Mi"
         cpu: "150m"

 