apiVersion: v1
kind: Pod
metadata:
  name: env
  labels: 
    project: roboshop
spec:
  containers:
  -  name: nginx
     image: nginx
     env:
     - name: COURSE
       value: "KUBERNETIS"
     - name: TRAINER
       value: "siva kumar"
    