apiVersion: v1
kind: Service
metadat: 
  name: service-np 
  labels:
   purpose: service-np-demo
  spec:
    type: NodePort 
    selector: 
      project: roboshop
      purpose: service-demo
      environment: dev
    ports: 
     - protocal: TCP  
       port: 80
       targetPort: 80
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
    purpose: service-demo
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx


