apiVersion: v1 
kind: Service 
metadata:
  name: sc-headless-svc 
  labels:
    purpose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    purpose: statefulset
    project: roboshop
---
apiVersion: v1 
kind: Service 
metadata:
  name: sc-normal-svc 
  labels:
    purpose: statefulset
    project: roboshop
spec:
  ports:
  - port: 80
  
  selector:
    purpose: statefulset
    project: roboshop

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sc-headless
spec:
  selector:
    matchLabels:
      purpose: statefulset
      project: roboshop
 # has to match .spec.template.metadata.labels
  serviceName: "sc-headless-svc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        purpose: statefulset
        project: roboshop
 # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "efs-roboshop"
      resources:
        requests:
          storage: 2Gi